apiVersion: v1
kind: Service
metadata:
  name: debezium-connect
  labels:
    app: debezium-connect
spec:
  selector:
    app: debezium-connect
  ports:
    - name: http
      port: 8083
      targetPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-connect
  labels:
    app: debezium-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium-connect
  template:
    metadata:
      labels:
        app: debezium-connect
    spec:
      containers:
        - name: debezium-connect
          image: quay.io/debezium/connect:2.5
          ports:
            - containerPort: 8083
          env:
            - name: BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: GROUP_ID
              value: "1"
            - name: CONFIG_STORAGE_TOPIC
              value: connect-configs
            - name: OFFSET_STORAGE_TOPIC
              value: connect-offsets
            - name: STATUS_STORAGE_TOPIC
              value: connect-statuses

